
baseurl="https://nangia.in"
languageCode='en-us'
title="Ruminations"
theme='Hugo-Octopress'

# Needed so we can serve the example website without extra switches
themesDir = "./themes"

# Disqus shortcode
# Disable comments for any individual post by adding "comments: false" in its frontmatter
# Note it's not under [params] anymore
# disqusShortname = "Your disqus shortname"

# Number of blog posts in each pagination page
paginate = 6

# [permalinks]
# post = "/blog/:year-:month-:day-:title/" # change the post URL to look like the old ones

[frontmatter]
  lastmod = ["lastmod", ":git", "date", "publishDate"]

[params]
compactIndex = true
sidebarTags = "Tags"

  # Generate taxonomy pages
generateTaxonomyList = true
cleanDestinationDir = true
  # --- Start sidebar options ---
  # Number of last posts that will be displayed in the sidebar - set to 0 or remove to hide this section
  sidebarRecentLimit = 0
  math = true
  # Sidebar header - passed to markdownify so you can write markdown here
  sidebarHeader = "Elsewhere on the Internet"

  # Sidebar text also supports markdown
  # New lines can be added with two spaces at the end of line. New paragraphs can be added with two an empty line.
  # when adding two new lines, remember to remove the indentation otherwise the new line will be treated as a codeblock
  sidebarText = """And this is where you can find me elsewhere on the internet. 
  """
  # Sidebar menu - if true will add a sidebar menu between sidebar text and recent posts
  sidebarMenuEnabled = false
  sidebarMenuHeader = "Sidebar Links"

  # sidebar links
  github = "https://github.com/nangia"
  # bitbucket = "https://bitbucket.org/parsiya/"
  twitter = "https://x.com/SNChd"
  linkedin = "https://www.linkedin.com/in/sandeepnangia/"
  # --- End sidebar options ---




  # If set to true, navigation menu links will open in a new window with the exception of links to root ("/")
  # If this item does not exist or set to false, then navigation menu links will open in the same window
  navigationNewWindow = true

  # If false, all of blog post will appear on front page (and in pagination)
  truncate = false

  # Author's name (appears in meta tags and under posts)
  author = "Sandeep Nangia"

  # This text appears in the site header under website title
  subtitle = "by Sandeep Nangia"

  # Search engine URL
  searchEngineURL = "https://www.google.com/search"

  # Text of the "Continue Reading" label. Supports markdown and inline HTML.
  # For example, &rarr; == right arrow.
  continueReadingText = "Read on &rarr;"

  # Switch to true to enable RSS icon link
  rss = true

  # Set to true to use a text label for RSS instead of an icon
  # This is overwritten by the "rss" setting
  textrss = false

  # Website's default description
  description = "Ruminations by Sandeep Nangia on various things of interest to him - Sanskrit, Philosophy, Mathamatics, Technology et al."

  # 404.html header and text - both support markdown
  notFoundHeader = "There's nothing here"

  notFoundText = """Please either go back or use the navigation/sidebar menus.
  """

  # Set to true to hide ReadingTime on posts
  disableReadingTime = true

  # Set to true to disable downloading of remote Google fonts
  disableGoogleFonts = true

[taxonomies]
  category = 'categories'
  tag = 'tags'




# Menu
# If navigationNewWindow (under [params]) is set to true then all links except root ("/") will open in a new window
# If it does not exist or is set to false then links will open in the same window
[[menu.main]]
  Name = "All"
  URL = "/"
  weight = -5

[[menu.main]]
  Name = "Tech"
  URL = "/categories/tech/"
  weight = -4

[[menu.main]]
  Name = "Sanskrit"
  URL = "/categories/sanskrit/"
  weight = -3


[[menu.main]]
  Name = "About Me"
  URL = "/page/about/"
  weight = 0


# Sidebar menus
# Enable with "sidebarMenuEnabled = true" under [params]
# Header text is "sidebarMenuHeader" under [params]
# [[menu.sidebar]]
#  Name = "example.net"
#  URL = "https://www.example.net"
#  weight = 0

# [[menu.sidebar]]
#  Name = "This theme on Github"
#  URL = "https://www.github.com/parsiya/hugo-octopress"
#  weight = 1

[markup]
  [markup.tableOfContents]
    endLevel = 8
    startLevel = 1
  [markup.highlight]
    style = "solarized-dark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]








